parser: '@typescript-eslint/parser'
extends:
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2021
  sourceType: 'module'
plugins:
  - 'import'
  - '@typescript-eslint/eslint-plugin'
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - ignoreRestSiblings: true
  'react/jsx-no-undef': off
  'react/jsx-uses-react': off
  'react/jsx-curly-brace-presence': 'warn'
  'react/react-in-jsx-scope': off
  'prettier/prettier': 'warn'
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-non-null-asserted-optional-chain': off
overrides:
  - files:
      - '*.test.tsx'
    rules:
      '@typescript-eslint/no-empty-function': 0
settings:
  react:
    version: 'detect'
ignorePatterns:
  - 'src/generated/**'
