name: CD
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: //npm.pkg.github.com/
      - name: Install Packages
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Format
        run: yarn run format

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: //npm.pkg.github.com/
      - name: Install Packages
        run: yarn install --frozen-lockfile
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: main
          folder: public
