name: CI
on: push
branch: main
jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: //npm.pkg.github.com/
      - name: Install Packages
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Format
        run: yarn run format
      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v4
